#!/usr/bin/python3
# syntax.py by Bill Weinman [http://bw.org/]
# This is an exercise file from Python 3 Essential Training on lynda.com
# Copyright 2010 The BearHeart Group, LLC

def main():
    print("This is the syntax.py file.")
    x = 3
    y = 3 + x
    print(y)
    
if __name__ == "__main__": main()
